#ifndef GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
#define GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H

<<<<<<< HEAD
#define EFFECT_HIT 0
#define EFFECT_SLEEP 1
#define EFFECT_POISON_HIT 2
#define EFFECT_ABSORB 3
#define EFFECT_BURN_HIT 4
#define EFFECT_FREEZE_HIT 5
#define EFFECT_PARALYZE_HIT 6
#define EFFECT_EXPLOSION 7
#define EFFECT_DREAM_EATER 8
#define EFFECT_MIRROR_MOVE 9
#define EFFECT_ATTACK_UP 10
#define EFFECT_DEFENSE_UP 11
#define EFFECT_SPEED_UP 12
#define EFFECT_SPECIAL_ATTACK_UP 13
#define EFFECT_SPECIAL_DEFENSE_UP 14
#define EFFECT_ACCURACY_UP 15
#define EFFECT_EVASION_UP 16
#define EFFECT_ALWAYS_HIT 17
#define EFFECT_ATTACK_DOWN 18
#define EFFECT_DEFENSE_DOWN 19
#define EFFECT_SPEED_DOWN 20
#define EFFECT_SPECIAL_ATTACK_DOWN 21  // unused
#define EFFECT_SPECIAL_DEFENSE_DOWN 22  // unused
#define EFFECT_ACCURACY_DOWN 23
#define EFFECT_EVASION_DOWN 24
#define EFFECT_HAZE 25
#define EFFECT_BIDE 26
#define EFFECT_RAMPAGE 27
#define EFFECT_ROAR 28
#define EFFECT_MULTI_HIT 29
#define EFFECT_CONVERSION 30
#define EFFECT_FLINCH_HIT 31
#define EFFECT_RESTORE_HP 32
#define EFFECT_TOXIC 33
#define EFFECT_PAY_DAY 34
#define EFFECT_LIGHT_SCREEN 35
#define EFFECT_TRI_ATTACK 36
#define EFFECT_REST 37
#define EFFECT_OHKO 38
#define EFFECT_RAZOR_WIND 39
#define EFFECT_SUPER_FANG 40
#define EFFECT_DRAGON_RAGE 41
#define EFFECT_TRAP 42
#define EFFECT_HIGH_CRITICAL 43
#define EFFECT_DOUBLE_HIT 44
#define EFFECT_RECOIL_IF_MISS 45
#define EFFECT_MIST 46
#define EFFECT_FOCUS_ENERGY 47
#define EFFECT_RECOIL 48
#define EFFECT_CONFUSE 49
#define EFFECT_ATTACK_UP_2 50
#define EFFECT_DEFENSE_UP_2 51
#define EFFECT_SPEED_UP_2 52
#define EFFECT_SPECIAL_ATTACK_UP_2 53
#define EFFECT_SPECIAL_DEFENSE_UP_2 54
#define EFFECT_ACCURACY_UP_2 55
#define EFFECT_EVASION_UP_2 56
#define EFFECT_TRANSFORM 57
#define EFFECT_ATTACK_DOWN_2 58
#define EFFECT_DEFENSE_DOWN_2 59
#define EFFECT_SPEED_DOWN_2 60
#define EFFECT_SPECIAL_ATTACK_DOWN_2 61
#define EFFECT_SPECIAL_DEFENSE_DOWN_2 62
#define EFFECT_ACCURACY_DOWN_2 63
#define EFFECT_EVASION_DOWN_2 64
#define EFFECT_REFLECT 65
#define EFFECT_POISON 66
#define EFFECT_PARALYZE 67
#define EFFECT_ATTACK_DOWN_HIT 68
#define EFFECT_DEFENSE_DOWN_HIT 69
#define EFFECT_SPEED_DOWN_HIT 70
#define EFFECT_SPECIAL_ATTACK_DOWN_HIT 71
#define EFFECT_SPECIAL_DEFENSE_DOWN_HIT 72
#define EFFECT_ACCURACY_DOWN_HIT 73
#define EFFECT_EVASION_DOWN_HIT 74
#define EFFECT_SKY_ATTACK 75
#define EFFECT_CONFUSE_HIT 76
#define EFFECT_TWINEEDLE 77
#define EFFECT_VITAL_THROW 78
#define EFFECT_SUBSTITUTE 79
#define EFFECT_RECHARGE 80
#define EFFECT_RAGE 81
#define EFFECT_MIMIC 82
#define EFFECT_METRONOME 83
#define EFFECT_LEECH_SEED 84
#define EFFECT_SPLASH 85
#define EFFECT_DISABLE 86
#define EFFECT_LEVEL_DAMAGE 87
#define EFFECT_PSYWAVE 88
#define EFFECT_COUNTER 89
#define EFFECT_ENCORE 90
#define EFFECT_PAIN_SPLIT 91
#define EFFECT_SNORE 92
#define EFFECT_CONVERSION_2 93
#define EFFECT_LOCK_ON 94
#define EFFECT_SKETCH 95
#define EFFECT_UNUSED_60 96  // thaw
#define EFFECT_SLEEP_TALK 97
#define EFFECT_DESTINY_BOND 98
#define EFFECT_FLAIL 99
#define EFFECT_SPITE 100
#define EFFECT_FALSE_SWIPE 101
#define EFFECT_HEAL_BELL 102
#define EFFECT_QUICK_ATTACK 103
#define EFFECT_TRIPLE_KICK 104
#define EFFECT_THIEF 105
#define EFFECT_MEAN_LOOK 106
#define EFFECT_NIGHTMARE 107
#define EFFECT_MINIMIZE 108
#define EFFECT_CURSE 109
#define EFFECT_UNUSED_6E 110
#define EFFECT_PROTECT 111
#define EFFECT_SPIKES 112
#define EFFECT_FORESIGHT 113
#define EFFECT_PERISH_SONG 114
#define EFFECT_SANDSTORM 115
#define EFFECT_ENDURE 116
#define EFFECT_ROLLOUT 117
#define EFFECT_SWAGGER 118
#define EFFECT_FURY_CUTTER 119
#define EFFECT_ATTRACT 120
#define EFFECT_RETURN 121
#define EFFECT_PRESENT 122
#define EFFECT_FRUSTRATION 123
#define EFFECT_SAFEGUARD 124
#define EFFECT_THAW_HIT 125
#define EFFECT_MAGNITUDE 126
#define EFFECT_BATON_PASS 127
#define EFFECT_PURSUIT 128
#define EFFECT_RAPID_SPIN 129
#define EFFECT_SONICBOOM 130
#define EFFECT_UNUSED_83 131
#define EFFECT_MORNING_SUN 132
#define EFFECT_SYNTHESIS 133
#define EFFECT_MOONLIGHT 134
#define EFFECT_HIDDEN_POWER 135
#define EFFECT_RAIN_DANCE 136
#define EFFECT_SUNNY_DAY 137
#define EFFECT_DEFENSE_UP_HIT 138
#define EFFECT_ATTACK_UP_HIT 139
#define EFFECT_ALL_STATS_UP_HIT 140
#define EFFECT_UNUSED_8D 141  // incomplete fake out in gen 2
#define EFFECT_BELLY_DRUM 142
#define EFFECT_PSYCH_UP 143
#define EFFECT_MIRROR_COAT 144
#define EFFECT_SKULL_BASH 145
#define EFFECT_TWISTER 146
#define EFFECT_EARTHQUAKE 147
#define EFFECT_FUTURE_SIGHT 148
#define EFFECT_GUST 149
#define EFFECT_FLINCH_MINIMIZE_HIT 150  // STOMP ASTONISH EXTRASENSORY NEEDLE_ARM
#define EFFECT_SOLAR_BEAM 151
#define EFFECT_THUNDER 152
#define EFFECT_TELEPORT 153
#define EFFECT_BEAT_UP 154
#define EFFECT_SEMI_INVULNERABLE 155
#define EFFECT_DEFENSE_CURL 156
#define EFFECT_SOFTBOILED 157
#define EFFECT_FAKE_OUT 158
#define EFFECT_UPROAR 159
#define EFFECT_STOCKPILE 160
#define EFFECT_SPIT_UP 161
#define EFFECT_SWALLOW 162
#define EFFECT_UNUSED_A3 163
#define EFFECT_HAIL 164
#define EFFECT_TORMENT 165
#define EFFECT_FLATTER 166
#define EFFECT_WILL_O_WISP 167
#define EFFECT_MEMENTO 168
#define EFFECT_FACADE 169
#define EFFECT_FOCUS_PUNCH 170
#define EFFECT_SMELLINGSALT 171
#define EFFECT_FOLLOW_ME 172
#define EFFECT_NATURE_POWER 173
#define EFFECT_CHARGE 174
#define EFFECT_TAUNT 175
#define EFFECT_HELPING_HAND 176
#define EFFECT_TRICK 177
#define EFFECT_ROLE_PLAY 178
#define EFFECT_WISH 179
#define EFFECT_ASSIST 180
#define EFFECT_INGRAIN 181
#define EFFECT_SUPERPOWER 182
#define EFFECT_MAGIC_COAT 183
#define EFFECT_RECYCLE 184
#define EFFECT_REVENGE 185
#define EFFECT_BRICK_BREAK 186
#define EFFECT_YAWN 187
#define EFFECT_KNOCK_OFF 188
#define EFFECT_ENDEAVOR 189
#define EFFECT_ERUPTION 190
#define EFFECT_SKILL_SWAP 191
#define EFFECT_IMPRISON 192
#define EFFECT_REFRESH 193
#define EFFECT_GRUDGE 194
#define EFFECT_SNATCH 195
#define EFFECT_LOW_KICK 196
#define EFFECT_SECRET_POWER 197
#define EFFECT_DOUBLE_EDGE 198
#define EFFECT_TEETER_DANCE 199
#define EFFECT_BLAZE_KICK 200
#define EFFECT_MUD_SPORT 201
#define EFFECT_POISON_FANG 202
#define EFFECT_WEATHER_BALL 203
#define EFFECT_OVERHEAT 204
#define EFFECT_TICKLE 205
#define EFFECT_COSMIC_POWER 206
#define EFFECT_SKY_UPPERCUT 207
#define EFFECT_BULK_UP 208
#define EFFECT_POISON_TAIL 209
#define EFFECT_WATER_SPORT 210
#define EFFECT_CALM_MIND 211
#define EFFECT_DRAGON_DANCE 212
#define EFFECT_CAMOUFLAGE 213

#define NUM_BATTLE_MOVE_EFFECTS 214
=======
enum __attribute__((packed)) BattleMoveEffects
{
    EFFECT_PLACEHOLDER,
    EFFECT_HIT,
    EFFECT_NON_VOLATILE_STATUS,
    EFFECT_ABSORB,
    EFFECT_EXPLOSION,
    EFFECT_MISTY_EXPLOSION, // Same as EFFECT_EXPLOSION but it's boosted on Misty Terrain
    EFFECT_DREAM_EATER, // Same as EFFECT_ABSORB but it can only be used on sleeping targets
    EFFECT_MIRROR_MOVE,
    EFFECT_ATTACK_UP,
    EFFECT_DEFENSE_UP,
    EFFECT_SPEED_UP,
    EFFECT_SPECIAL_ATTACK_UP,
    EFFECT_SPECIAL_DEFENSE_UP,
    EFFECT_ACCURACY_UP,
    EFFECT_EVASION_UP,
    EFFECT_SPECIAL_ATTACK_UP_3,
    EFFECT_ATTACK_DOWN,
    EFFECT_DEFENSE_DOWN,
    EFFECT_SPEED_DOWN,
    EFFECT_SPECIAL_ATTACK_DOWN,
    EFFECT_SPECIAL_DEFENSE_DOWN,
    EFFECT_ACCURACY_DOWN,
    EFFECT_EVASION_DOWN,
    EFFECT_HAZE,
    EFFECT_BIDE,
    EFFECT_ROAR,
    EFFECT_MULTI_HIT,
    EFFECT_CONVERSION,
    EFFECT_RESTORE_HP,
    EFFECT_LIGHT_SCREEN,
    EFFECT_REST,
    EFFECT_OHKO,
    EFFECT_SHEER_COLD, // Same as EFFECT_OHKO but Ice-types are immune to it and has decreased accuracy for non Ice-type users.
    EFFECT_FUSION_COMBO,
    EFFECT_FIXED_PERCENT_DAMAGE,
    EFFECT_FIXED_HP_DAMAGE,
    EFFECT_HEAL_BLOCK,
    EFFECT_RECOIL_IF_MISS,
    EFFECT_MIST,
    EFFECT_FOCUS_ENERGY,
    EFFECT_CONFUSE,
    EFFECT_ATTACK_UP_2,
    EFFECT_DEFENSE_UP_2,
    EFFECT_SPEED_UP_2,
    EFFECT_SPECIAL_ATTACK_UP_2,
    EFFECT_SPECIAL_DEFENSE_UP_2,
    EFFECT_ACCURACY_UP_2,
    EFFECT_EVASION_UP_2,
    EFFECT_TRANSFORM,
    EFFECT_ATTACK_DOWN_2,
    EFFECT_DEFENSE_DOWN_2,
    EFFECT_SPEED_DOWN_2,
    EFFECT_SPECIAL_ATTACK_DOWN_2,
    EFFECT_SPECIAL_DEFENSE_DOWN_2,
    EFFECT_ACCURACY_DOWN_2,
    EFFECT_EVASION_DOWN_2,
    EFFECT_REFLECT,
    EFFECT_TWO_TURNS_ATTACK,
    EFFECT_SUBSTITUTE,
    EFFECT_RAGE,
    EFFECT_MIMIC,
    EFFECT_METRONOME,
    EFFECT_LEECH_SEED,
    EFFECT_DO_NOTHING,
    EFFECT_HOLD_HANDS,
    EFFECT_CELEBRATE,
    EFFECT_HAPPY_HOUR,
    EFFECT_DISABLE,
    EFFECT_LEVEL_DAMAGE,
    EFFECT_PSYWAVE,
    EFFECT_COUNTER,
    EFFECT_ENCORE,
    EFFECT_PAIN_SPLIT,
    EFFECT_SNORE,
    EFFECT_CONVERSION_2,
    EFFECT_LOCK_ON,
    EFFECT_SKETCH,
    EFFECT_SLEEP_TALK,
    EFFECT_DESTINY_BOND,
    EFFECT_FLAIL,
    EFFECT_SPITE,
    EFFECT_FALSE_SWIPE,
    EFFECT_HEAL_BELL,
    EFFECT_TRIPLE_KICK,
    EFFECT_MEAN_LOOK,
    EFFECT_NIGHTMARE,
    EFFECT_MINIMIZE,
    EFFECT_CURSE,
    EFFECT_HEALING_WISH,
    EFFECT_PROTECT,
    EFFECT_SPIKES,
    EFFECT_FORESIGHT,
    EFFECT_PERISH_SONG,
    EFFECT_SANDSTORM,
    EFFECT_ENDURE,
    EFFECT_ROLLOUT,
    EFFECT_SWAGGER,
    EFFECT_FURY_CUTTER,
    EFFECT_ATTRACT,
    EFFECT_RETURN,
    EFFECT_PRESENT,
    EFFECT_FRUSTRATION,
    EFFECT_SAFEGUARD,
    EFFECT_MAGNITUDE,
    EFFECT_BATON_PASS,
    EFFECT_PURSUIT,
    EFFECT_CAPTIVATE,
    EFFECT_MORNING_SUN,
    EFFECT_SYNTHESIS,
    EFFECT_MOONLIGHT,
    EFFECT_HIDDEN_POWER,
    EFFECT_RAIN_DANCE,
    EFFECT_SUNNY_DAY,
    EFFECT_FELL_STINGER,
    EFFECT_BELLY_DRUM,
    EFFECT_PSYCH_UP,
    EFFECT_MIRROR_COAT,
    EFFECT_EARTHQUAKE,
    EFFECT_FUTURE_SIGHT,
    EFFECT_SOLAR_BEAM,
    EFFECT_TELEPORT,
    EFFECT_BEAT_UP,
    EFFECT_SEMI_INVULNERABLE,
    EFFECT_DEFENSE_CURL,
    EFFECT_SOFTBOILED, // differences vs Recover - can be used outside of battle to restore HP
    EFFECT_FIRST_TURN_ONLY,
    EFFECT_UPROAR,
    EFFECT_STOCKPILE,
    EFFECT_SPIT_UP,
    EFFECT_SWALLOW,
    EFFECT_WORRY_SEED,
    EFFECT_HAIL,
    EFFECT_TORMENT,
    EFFECT_FLATTER,
    EFFECT_MEMENTO,
    EFFECT_FACADE,
    EFFECT_FOCUS_PUNCH,
    EFFECT_DOUBLE_POWER_ON_ARG_STATUS,
    EFFECT_FOLLOW_ME,
    EFFECT_NATURE_POWER,
    EFFECT_CHARGE,
    EFFECT_TAUNT,
    EFFECT_HELPING_HAND,
    EFFECT_TRICK,
    EFFECT_ROLE_PLAY,
    EFFECT_WISH,
    EFFECT_ASSIST,
    EFFECT_INGRAIN,
    EFFECT_MAGIC_COAT,
    EFFECT_RECYCLE,
    EFFECT_REVENGE,
    EFFECT_BRICK_BREAK,
    EFFECT_YAWN,
    EFFECT_KNOCK_OFF,
    EFFECT_STEAL_ITEM,
    EFFECT_ENDEAVOR,
    EFFECT_POWER_BASED_ON_USER_HP,
    EFFECT_SKILL_SWAP,
    EFFECT_IMPRISON,
    EFFECT_REFRESH,
    EFFECT_GRUDGE,
    EFFECT_SNATCH,
    EFFECT_LOW_KICK,
    EFFECT_HIT_ESCAPE,
    EFFECT_MUD_SPORT,
    EFFECT_WEATHER_BALL,
    EFFECT_TICKLE,
    EFFECT_COSMIC_POWER,
    EFFECT_BULK_UP,
    EFFECT_WATER_SPORT,
    EFFECT_CALM_MIND,
    EFFECT_DRAGON_DANCE,
    EFFECT_CAMOUFLAGE,
    EFFECT_PLEDGE,
    EFFECT_FLING,
    EFFECT_NATURAL_GIFT,
    EFFECT_POWER_BASED_ON_TARGET_HP,
    EFFECT_ASSURANCE,
    EFFECT_TRUMP_CARD,
    EFFECT_ACROBATICS,
    EFFECT_HEAT_CRASH,
    EFFECT_PUNISHMENT,
    EFFECT_STORED_POWER,
    EFFECT_ELECTRO_BALL,
    EFFECT_GYRO_BALL,
    EFFECT_ECHOED_VOICE,
    EFFECT_PAYBACK,
    EFFECT_ROUND,
    EFFECT_BRINE,
    EFFECT_RETALIATE,
    EFFECT_FOUL_PLAY,
    EFFECT_PSYSHOCK,
    EFFECT_ROOST,
    EFFECT_GRAVITY,
    EFFECT_MIRACLE_EYE,
    EFFECT_TAILWIND,
    EFFECT_EMBARGO,
    EFFECT_AQUA_RING,
    EFFECT_TRICK_ROOM,
    EFFECT_WONDER_ROOM,
    EFFECT_MAGIC_ROOM,
    EFFECT_MAGNET_RISE,
    EFFECT_TOXIC_SPIKES,
    EFFECT_GASTRO_ACID,
    EFFECT_STEALTH_ROCK,
    EFFECT_TELEKINESIS,
    EFFECT_POWER_SWAP,
    EFFECT_GUARD_SWAP,
    EFFECT_HEART_SWAP,
    EFFECT_POWER_SPLIT,
    EFFECT_GUARD_SPLIT,
    EFFECT_STICKY_WEB,
    EFFECT_METAL_BURST,
    EFFECT_LUCKY_CHANT,
    EFFECT_SUCKER_PUNCH,
    EFFECT_SIMPLE_BEAM,
    EFFECT_ENTRAINMENT,
    EFFECT_HEAL_PULSE,
    EFFECT_QUASH,
    EFFECT_ION_DELUGE,
    EFFECT_SUPER_EFFECTIVE_ON_ARG,
    EFFECT_TOPSY_TURVY,
    EFFECT_MISTY_TERRAIN,
    EFFECT_GRASSY_TERRAIN,
    EFFECT_ELECTRIC_TERRAIN,
    EFFECT_PSYCHIC_TERRAIN,
    EFFECT_ATTACK_ACCURACY_UP,
    EFFECT_ATTACK_SPATK_UP,
    EFFECT_TWO_TYPED_MOVE,
    EFFECT_ME_FIRST,
    EFFECT_QUIVER_DANCE,
    EFFECT_COIL,
    EFFECT_ELECTRIFY,
    EFFECT_REFLECT_TYPE,
    EFFECT_SOAK,
    EFFECT_GROWTH,
    EFFECT_LAST_RESORT,
    EFFECT_SHELL_SMASH,
    EFFECT_SHIFT_GEAR,
    EFFECT_DEFENSE_UP_3,
    EFFECT_NOBLE_ROAR,
    EFFECT_VENOM_DRENCH,
    EFFECT_TOXIC_THREAD,
    EFFECT_HIT_SWITCH_TARGET,
    EFFECT_FINAL_GAMBIT,
    EFFECT_CHANGE_TYPE_ON_ITEM,
    EFFECT_AUTOTOMIZE,
    EFFECT_COPYCAT,
    EFFECT_DEFOG,
    EFFECT_HIT_ENEMY_HEAL_ALLY,
    EFFECT_SYNCHRONOISE,
    EFFECT_PSYCHO_SHIFT,
    EFFECT_POWER_TRICK,
    EFFECT_AFTER_YOU,
    EFFECT_BESTOW,
    EFFECT_ROTOTILLER,
    EFFECT_FLOWER_SHIELD,
    EFFECT_SPEED_SWAP,
    EFFECT_REVELATION_DANCE,
    EFFECT_AURORA_VEIL,
    EFFECT_THIRD_TYPE,
    EFFECT_ACUPRESSURE,
    EFFECT_AROMATIC_MIST,
    EFFECT_POWDER,
    EFFECT_BELCH,
    EFFECT_PARTING_SHOT,
    EFFECT_MAT_BLOCK,
    EFFECT_STOMPING_TANTRUM,
    EFFECT_INSTRUCT,
    EFFECT_LASER_FOCUS,
    EFFECT_MAGNETIC_FLUX,
    EFFECT_GEAR_UP,
    EFFECT_STRENGTH_SAP,
    EFFECT_PURIFY,
    EFFECT_FAIL_IF_NOT_ARG_TYPE,
    EFFECT_SHORE_UP,
    EFFECT_GEOMANCY,
    EFFECT_FAIRY_LOCK,
    EFFECT_ALLY_SWITCH,
    EFFECT_BODY_PRESS,
    EFFECT_JUNGLE_HEALING,
    EFFECT_COACHING,
    EFFECT_LASH_OUT,
    EFFECT_GRASSY_GLIDE,
    EFFECT_DYNAMAX_DOUBLE_DMG,
    EFFECT_DECORATE,
    EFFECT_SNIPE_SHOT,
    EFFECT_STRUGGLE,
    EFFECT_STUFF_CHEEKS,
    EFFECT_GRAV_APPLE,
    EFFECT_HYPERSPACE_FURY,
    EFFECT_AURA_WHEEL,
    EFFECT_PHOTON_GEYSER,
    EFFECT_TERRAIN_PULSE,
    EFFECT_NO_RETREAT,
    EFFECT_TAR_SHOT,
    EFFECT_POLTERGEIST,
    EFFECT_OCTOLOCK,
    EFFECT_CLANGOROUS_SOUL,
    EFFECT_BOLT_BEAK,
    EFFECT_SKY_DROP,
    EFFECT_EXPANDING_FORCE,
    EFFECT_RISING_VOLTAGE,
    EFFECT_BEAK_BLAST,
    EFFECT_COURT_CHANGE,
    EFFECT_MAX_HP_50_RECOIL,
    EFFECT_CHLOROBLAST, // Same effect as EFFECT_MAX_HP_50_RECOIL but follows the same rules as EFFECT_RECOIL
    EFFECT_EXTREME_EVOBOOST,
    EFFECT_HIT_SET_TERRAIN,
    EFFECT_DARK_VOID,
    EFFECT_VICTORY_DANCE,
    EFFECT_TEATIME,
    EFFECT_ATTACK_UP_USER_ALLY,
    EFFECT_SHELL_TRAP,
    EFFECT_PSYBLADE,
    EFFECT_HYDRO_STEAM,
    EFFECT_REVIVAL_BLESSING,
    EFFECT_SNOWSCAPE,
    EFFECT_TAKE_HEART,
    EFFECT_COLLISION_COURSE,
    EFFECT_CORROSIVE_GAS,
    EFFECT_POPULATION_BOMB,
    EFFECT_CHILLY_RECEPTION,
    EFFECT_MAX_MOVE,
    EFFECT_GLAIVE_RUSH,
    EFFECT_RAGING_BULL,
    EFFECT_RAGE_FIST,
    EFFECT_DOODLE,
    EFFECT_FILLET_AWAY,
    EFFECT_IVY_CUDGEL,
    EFFECT_FICKLE_BEAM,
    EFFECT_SHED_TAIL,
    EFFECT_UPPER_HAND,
    EFFECT_DRAGON_CHEER,
    EFFECT_LAST_RESPECTS,
    EFFECT_TIDY_UP,
    EFFECT_SPICY_EXTRACT,
    EFFECT_TERA_BLAST,
    EFFECT_TERA_STARSTORM,
    EFFECT_DRAGON_DARTS,
    EFFECT_SHELL_SIDE_ARM,
    EFFECT_ORDER_UP,
    EFFECT_RAPID_SPIN,
    EFFECT_SPECTRAL_THIEF,
    EFFECT_RECOIL,
    EFFECT_SMACK_DOWN,
    EFFECT_LIFE_DEW,
    EFFECT_ICE_SPINNER, // Removes terrain unless attacker is removed from field either by fainting or ejected out
    EFFECT_STEEL_ROLLER, // Will fail if there is no terrain up but removes it regardless if attacker is removed from field or not
    EFFECT_STONE_AXE, // Not to be confused with MOVE_EFFECT_STEALTH_ROCK. They have two different activation timings.
    EFFECT_CEASELESS_EDGE, // Same applies to spikes
    NUM_BATTLE_MOVE_EFFECTS,
};
>>>>>>> 8eea132406f53e5857d1eec72181867b469bddfc

#endif  // GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
