#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F,
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F,
    HEAL_LOCATION_PETALBURG_CITY,
    HEAL_LOCATION_SLATEPORT_CITY,
    HEAL_LOCATION_MAUVILLE_CITY,
    HEAL_LOCATION_RUSTBORO_CITY,
    HEAL_LOCATION_FORTREE_CITY,
    HEAL_LOCATION_LILYCOVE_CITY,
    HEAL_LOCATION_MOSSDEEP_CITY,
    HEAL_LOCATION_SOOTOPOLIS_CITY,
    HEAL_LOCATION_EVER_GRANDE_CITY,
    HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE,
    HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE,
    HEAL_LOCATION_OLDALE_TOWN,
    HEAL_LOCATION_DEWFORD_TOWN,
    HEAL_LOCATION_LAVARIDGE_TOWN,
    HEAL_LOCATION_FALLARBOR_TOWN,
    HEAL_LOCATION_VERDANTURF_TOWN,
    HEAL_LOCATION_PACIFIDLOG_TOWN,
    HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE,
    HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR,
    HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST,
    HEAL_LOCATION_NEW_BARK_TOWN,
    HEAL_LOCATION_VIOLET_CITY,
    HEAL_LOCATION_AZALEA_TOWN,
    HEAL_LOCATION_GOLDENROD_CITY,
    HEAL_LOCATION_ECRUTEAK_CITY,
    HEAL_LOCATION_OLIVINE_CITY,
    HEAL_LOCATION_CIANWOOD_CITY,
    HEAL_LOCATION_MAHOGANYTOWN,
    HEAL_LOCATION_BLACKTHORN_CITY,
    HEAL_LOCATION_PALLET_TOWN,
    HEAL_LOCATION_VIRIDIAN_CITY,
    HEAL_LOCATION_PEWTER_CITY,
    HEAL_LOCATION_CERULEAN_CITY,
    HEAL_LOCATION_VERMILION_CITY,
    HEAL_LOCATION_LAVENDER_TOWN,
    HEAL_LOCATION_CELADON_CITY,
    HEAL_LOCATION_SAFFRON_CITY,
    HEAL_LOCATION_FUCHSIA_CITY,
    HEAL_LOCATION_CINNABAR_ISLAND,
    HEAL_LOCATION_MT_SILVER,
    HEAL_LOCATION_LAKE_OF_RAGE,
    HEAL_LOCATION_INDIGO_PLATEAU,
    HEAL_LOCATION_SAFARI_ZONE_GATE,
    HEAL_LOCATION_NEW_MAP1,
    HEAL_LOCATION_CHERRYGROVE_CITY,
    HEAL_LOCATION_NEW_BARK_TOWN_PLAYERS_HOUSE_2F,
    HEAL_LOCATION_ROUTE_32,
    HEAL_LOCATION_ROUTE26NORTH,
};

/*#define HEAL_LOCATION_NONE 0
#define HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F 1
#define HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE_2F 2
#define HEAL_LOCATION_PETALBURG_CITY 3
#define HEAL_LOCATION_SLATEPORT_CITY 4
#define HEAL_LOCATION_MAUVILLE_CITY 5
#define HEAL_LOCATION_RUSTBORO_CITY 6
#define HEAL_LOCATION_FORTREE_CITY 7
#define HEAL_LOCATION_LILYCOVE_CITY 8
#define HEAL_LOCATION_MOSSDEEP_CITY 9
#define HEAL_LOCATION_SOOTOPOLIS_CITY 10
#define HEAL_LOCATION_EVER_GRANDE_CITY 11
#define HEAL_LOCATION_LITTLEROOT_TOWN_BRENDANS_HOUSE 12
#define HEAL_LOCATION_LITTLEROOT_TOWN_MAYS_HOUSE 13
#define HEAL_LOCATION_OLDALE_TOWN 14
#define HEAL_LOCATION_DEWFORD_TOWN 15
#define HEAL_LOCATION_LAVARIDGE_TOWN 16
#define HEAL_LOCATION_FALLARBOR_TOWN 17
#define HEAL_LOCATION_VERDANTURF_TOWN 18
#define HEAL_LOCATION_PACIFIDLOG_TOWN 19
#define HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE 20
#define HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR 21
#define HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST 22
#define HEAL_LOCATION_NEW_BARK_TOWN 23
#define HEAL_LOCATION_VIOLET_CITY 24
#define HEAL_LOCATION_AZALEA_TOWN 25
#define HEAL_LOCATION_GOLDENROD_CITY 26
#define HEAL_LOCATION_ECRUTEAK_CITY 27
#define HEAL_LOCATION_OLIVINE_CITY 28
#define HEAL_LOCATION_CIANWOOD_CITY 29
#define HEAL_LOCATION_MAHOGANYTOWN 30
#define HEAL_LOCATION_BLACKTHORN_CITY 31
#define HEAL_LOCATION_PALLET_TOWN 32
#define HEAL_LOCATION_VIRIDIAN_CITY 33
#define HEAL_LOCATION_PEWTER_CITY 34
#define HEAL_LOCATION_CERULEAN_CITY 35
#define HEAL_LOCATION_VERMILION_CITY 36
#define HEAL_LOCATION_LAVENDER_TOWN 37
#define HEAL_LOCATION_CELADON_CITY 38
#define HEAL_LOCATION_SAFFRON_CITY 39
#define HEAL_LOCATION_FUCHSIA_CITY 40
#define HEAL_LOCATION_CINNABAR_ISLAND 41
#define HEAL_LOCATION_MT_SILVER 42
#define HEAL_LOCATION_LAKE_OF_RAGE 43
#define HEAL_LOCATION_INDIGO_PLATEAU 44
#define HEAL_LOCATION_SAFARI_ZONE_GATE 45
#define HEAL_LOCATION_NEW_MAP1 46
#define HEAL_LOCATION_CHERRYGROVE_CITY 47
#define HEAL_LOCATION_NEW_BARK_TOWN_PLAYERS_HOUSE_2F 48
#define HEAL_LOCATION_ROUTE_32 49
#define HEAL_LOCATION_ROUTE26NORTH 50*/

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
